import { PLATFORM_EXTENSION_SERVICE_DEFINITIONS } from "./platform-extensions.js";
import { PLATFORM_IO_SERVICE_DEFINITIONS } from "./platform-io.js";
import { PLATFORM_NOTIFICATION_SERVICE_DEFINITIONS } from "./platform-notification.js";
import { PLATFORM_SCHEDULER_SERVICE_DEFINITIONS } from "./platform-scheduler.js";

export const PLATFORM_SERVICE_DEFINITIONS = [
	...PLATFORM_IO_SERVICE_DEFINITIONS,
	...PLATFORM_SCHEDULER_SERVICE_DEFINITIONS,
	...PLATFORM_NOTIFICATION_SERVICE_DEFINITIONS,
	...PLATFORM_EXTENSION_SERVICE_DEFINITIONS,
] as const;
