import { SYSTEM_ALERTS_SERVICE_DEFINITIONS } from "./system-alerts.js";
import { SYSTEM_APP_SERVICE_DEFINITIONS } from "./system-app.js";
import { SYSTEM_OBSERVABILITY_SERVICE_DEFINITIONS } from "./system-observability.js";
import { SYSTEM_OPERATIONS_SERVICE_DEFINITIONS } from "./system-operations.js";
import { SYSTEM_POLICY_SERVICE_DEFINITIONS } from "./system-policy.js";

export const SYSTEM_SERVICE_DEFINITIONS = [
	...SYSTEM_APP_SERVICE_DEFINITIONS,
	...SYSTEM_OBSERVABILITY_SERVICE_DEFINITIONS,
	...SYSTEM_POLICY_SERVICE_DEFINITIONS,
	...SYSTEM_ALERTS_SERVICE_DEFINITIONS,
	...SYSTEM_OPERATIONS_SERVICE_DEFINITIONS,
] as const;
